export interface GameDocument {
  steam_appid: number;
  name: string;
  short_description?: string | null;
  detailed_description?: string | null;
  about_the_game?: string | null;
  header_image?: string | null;
  website?: string | null;
  screenshots?: string[] | null;
  movies?: string[] | null;
  release_date?: string | null; 
  last_updated: string;
  developers?: string[] | null;
  publishers?: string[] | null;
  is_early_access?: boolean | null;
  is_free?: boolean | null;
  total_reviews?: number | null;
  steam_app_type?: string | null;
  price_final?: number | null;
  price_currency?: string | null;
  price_initial?: number | null;
  discount_percent?: number | null;
  total_positive?: number | null;
  total_negative?: number | null;
  review_score_desc?: string | null;
  current_players?: number | null;
  tags?: string[] | null;
  genres?: string[] | null;
  controller_support?: string | null;
  metacritic_score?: number | null;
  metacritic_url?: string | null;
  platforms_windows?: boolean | null;
  platforms_mac?: boolean | null;
  platforms_linux?: boolean | null;
  pc_requirements?: any | null;
  mac_requirements?: any | null;
  linux_requirements?: any | null;
  supported_languages?: string | null;
  dlc?: number[] | null;
  required_age?: number | null;
  categories?: string[] | null;
  has_steam_achievements?: boolean | null;
  positive_rating_percentage?: number | null;
}

export interface WebApiData {
    type: string;
    name: string;
    steam_appid: number;
    short_description?: string;
    required_age?: number;
    is_free?: boolean;
    dlc?: number[];
    detailed_description?: string;
    about_the_game?: string;
    supported_languages?: string;
    header_image: string;
    website?: string;
    pc_requirements?: any;
    mac_requirements?: any;
    linux_requirements?: any;
    developers: string[];
    publishers: string[];
    price_overview?: { currency: string; initial: number; final: number; discount_percent: number; };
    metacritic?: { score: number; url: string; };
    categories?: { id: number; description: string }[];
    genres?: { id: string; description: string }[];
    screenshots?: {id: number; path_thumbnail: string; path_full: string;}[];
    movies?: {id: number; name: string; thumbnail: string; webm: any; mp4: {480: string; max: string;};}[];
    release_date: { coming_soon: boolean; date: string; };
    review_summary?: any;
    player_count?: number;
    platforms?: { windows: boolean; mac: boolean; linux: boolean; };
    achievements?: { total: number; };
}
