name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # ----------------- API Checks -----------------
      - name: API - Install Dependencies
        run: npm install --prefix api

      - name: API - Check for Vulnerabilities
        run: npm audit --prefix api --audit-level=high

      - name: API - Run Linter
        run: npm run --prefix api lint

      - name: API - Run Build
        run: npm run --prefix api build

      # ----------------- Developer Dashboard Checks -----------------
      - name: Developer Dashboard - Install Dependencies
        run: npm install --prefix devdashboard

      - name: Developer Dashboard - Check for Vulnerabilities
        run: npm audit --prefix devdashboard --audit-level=high

      - name: Developer Dashboard - Run Linter
        run: npm run --prefix devdashboard lint

      - name: Developer Dashboard - Run Build
        run: npm run --prefix devdashboard build

      # ----------------- Dashboard Checks -----------------

      - name: User Dashboard - Install Dependencies
        run: npm install --prefix user-dashboard

      - name: User Dashboard - Check for Vulnerabilities
        run: npm audit --prefix user-dashboard --audit-level=high

      - name: User Dashboard - Run Linter
        run: npm run --prefix user-dashboard lint

      - name: User Dashboard - Run Build
        run: npm run --prefix user-dashboard build
#      - name: Build and Push API Image
#        uses: docker/build-push-action@v2 